In [1]:
import pandas as pd
df = pd.read_csv('csv/house.csv')

In [2]:
#Filtrando dados com condiçoes
filter1 = df.loc[(df['Rooms'] == 3) & (df['Type'] == 'h') & (df['Price'] >= 500000)]
filter1

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
7,Airport West,1/26 Highridge Cr,3,h,715000.0,SP,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63011,Doveton,12 Scarlet Dr,3,h,595000.0,PI,REMAX,31/03/2018,3177,South-Eastern Metropolitan,3533,28.8,Casey City Council
63017,Preston,229 Murray Rd,3,h,808000.0,S,RW,31/03/2018,3072,Northern Metropolitan,14577,8.4,Darebin City Council
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council

In [3]:
#Filtrando com regular expression
import re
filter2 = df.loc[df['Address'].str.contains('Turner st|Turner Rd', flags=re.I)]
filter2

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2859,Malvern East,24 Turner St,6,h,4700000.0,S,RT,3/03/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
4723,Highett,48 Turner Rd,2,h,832000.0,S,Buxton,3/09/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
4987,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
7501,Highett,28 Turner Rd,3,h,NaN,PI,Nick,4/08/2018,3190,Southern Metropolitan,4794,16.0,Bayside City Council
9647,Abbotsford,53 Turner St,2,h,NaN,S,Biggin,6/08/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
9648,Abbotsford,99 Turner St,2,h,NaN,S,Collins,6/08/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
14012,Berwick,4 Turner St,5,h,536000.0,S,O'Brien,8/04/2017,3806,Eastern Victoria,17093,35.2,Casey City Council
14745,Westmeadows,16 Turner St,3,h,NaN,SN,Stockdale,8/04/2017,3049,Northern Metropolitan,2474,16.5,Hume City Council
18960,Moonee Ponds,3/16 Turner St,2,u,550000.0,VB,Woodards,10/09/2016,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
19148,Abbotsford,106/119 Turner St,1,u,481000.0,SP,Purplebricks,10/12/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
19609,Highett,2/20 Turner Rd,2,u,730000.0,SP,Buxton,10/12/2016,3190,Southern Metropolitan,4794,16.0,Bayside City Council
20043,Westmeadows,14 Turner St,3,h,586000.0,S,Stockdale,10/12/2016,3049,Northern Metropolitan,2474,16.5,Hume City Council
20717,Langwarrin,49 Turner Rd,4,h,NaN,PI,UFirst,11/08/2018,3910,Eastern Victoria,8743,41.0,Frankston City Council
25081,Moonee Ponds,15/3 Turner St,3,t,732000.0,S,Nelson,13/10/2018,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
26305,Abbotsford,2 Turner St,3,h,1620000.0,S,Biggin,14/07/2018,3067,Northern Metropolitan,4019,3.0,Yarra City Council
29650,Briar Hill,10 Turner St,2,h,812000.0,S,Darren,16/06/2018,3088,Eastern Metropolitan,1390,16.1,Banyule City Council
36217,Westmeadows,25 Turner St,4,h,685000.0,S,Jason,18/06/2016,3049,Northern Metropolitan,2474,16.5,Hume City Council
39873,Highett,3/6 Turner Rd,3,u,NaN,PI,Buxton,20/05/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
41985,Highett,1/6 Turner Rd,4,h,921000.0,S,Buxton,22/04/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
42537,Malvern East,16 Turner St,4,h,NaN,S,Marshall,22/05/2016,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
45597,Highett,3/15 Turner Rd,2,u,770000.0,S,McGrath,23/09/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
47333,Malvern East,27 Turner St,2,h,1040000.0,S,Jellis,24/02/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
47843,Berwick,6 Turner St,4,h,1400000.0,VB,Peake,24/03/2018,3806,Eastern Victoria,17093,35.2,Casey City Council
49480,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
49890,Moonee Ponds,4/6 Turner St,2,u,600000.0,S,Woodards,24/09/2016,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
50254,Briar Hill,7 Turner St,4,h,1100000.0,S,Jellis,25/02/2017,3088,Eastern Metropolitan,1390,16.1,Banyule City Council
51364,Malvern East,29 Turner St,2,h,1010000.0,SP,Jellis,25/08/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
53753,Highett,2/4 Turner Rd,2,u,680500.0,S,Ray,26/08/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
57940,Abbotsford,210/125 Turner St,2,u,760000.0,S,Nelson,28/07/2018,3067,Northern Metropolitan,4019,3.0,Yarra City Council
57978,Berwick,5 Turner St,4,h,940000.0,SP,Ray,28/07/2018,3806,Eastern Victoria,17093,35.2,Casey City Council
58707,Highett,22 Turner Rd,3,h,1150000.0,SP,Buxton,28/08/2016,3190,Southern Metropolitan,4794,16.0,Bayside City Council

In [4]:
# Filtrando com Regx e conditions
filter3 = df.loc[df['Address'].str.contains('^59', flags=re.I) & (df['Price'] <= 500000)]
filter3

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
2220,Wallan,59 William St,3,h,424000.0,S,Ruralco,2/06/2018,3756,Northern Victoria,3988,44.2,Mitchell Shire Council
9096,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,6/01/2018,3429,Western Metropolitan,14092,31.7,Hume City Council
13089,Sunshine West,59 Felstead Av,3,h,465000.0,S,Bells,7/11/2016,3020,Western Metropolitan,6763,10.5,Brimbank City Council
13840,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,8/01/2018,3429,Western Metropolitan,14092,31.7,Hume City Council
19616,Hoppers Crossing,59 Aitken Av,3,h,421600.0,SP,Barry,10/12/2016,3029,Western Metropolitan,13830,18.4,Wyndham City Council
19623,Hoppers Crossing,59 Mossfiel Dr,3,h,453000.0,S,Triwest,10/12/2016,3029,Western Metropolitan,13830,18.4,Wyndham City Council
30441,Thomastown,59 Darebin Dr,3,h,478500.0,S,hockingstuart,16/07/2016,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
31889,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,16/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council
46682,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,23/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council
62903,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,30/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council

In [ ]:
#Moficicando dados na dataframe
df.loc[df['SellerG'] == 'Reginald',['Method']] = 'Pending'
df